version: '3.8'

services:
  specsystem:
    build: ./spec
    restart: always
    ports:
      - 8087:80
      - 443:443
    volumes:
      - ./spec:/app
      - ./spec_files:/app/spec/static
    depends_on:
      - sqlexpress

  sqlexpress:
    image: mcr.microsoft.com/azure-sql-edge:latest
    volumes:
      - events_mssql:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Passw@rd
    tmpfs:
      - /run

  phpserver:
    image: php:7.4-apache
    ports:
      - 8888:80
    volumes:
      - ./auth:/var/www/html
    environment:
      - APP_ID=94c7b180-d769-4a18-ac7a-dbc496bf5e4e
      - SECRET={replace_with_real_secret}
      - LOGIN_URL=https://login.microsoftonline.com/43754c3b-6e44-4fc9-8b0a-304ac51f69a1/oauth2/v2.0/authorize
      - REDIRECT_URL=http://localhost:8888/
      - SPEC_LOGIN_URL=http://localhost:8087/accounts/login/
      - SECRET_JWT=fN5.Oo52zFZ4Kn9k

volumes:
  events_mssql:
